/*
* Copyright (c): it@M - Dienstleister fuer Informations- und Telekommunikationstechnik
* der Landeshauptstadt Muenchen, 2018
*/
package de.muenchen.testproject.admin.thebackend.service.rest;

import java.math.BigDecimal;
import org.junit.Assert;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;


import de.muenchen.testproject.admin.thebackend.service.MicroServiceApplication;
import de.muenchen.testproject.admin.thebackend.service.gen.domain.DateEntity_;

/*
 * This file will NOT be overwritten by Barrakuda.
 * This file was automatically generated by Barrakuda.
 */
@RunWith(SpringJUnit4ClassRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT, properties = {"spring.datasource.url=jdbc:h2:mem:testproject;DB_CLOSE_ON_EXIT=FALSE"})
@ContextConfiguration(classes={MicroServiceApplication.class})
@ActiveProfiles("test, no-security")
public class DateEntity_Repository_Test {

	@Autowired
	DateEntity_Repository repository;
	
	
	@Test
	@Transactional(propagation=Propagation.REQUIRED, readOnly=false, noRollbackFor=Exception.class)
	public void testSave(){
	    
	    // initialize
	    DateEntity_ original = new DateEntity_();
	    original.setTheDate(java.time.LocalDate.parse("12.12.2012",java.time.format.DateTimeFormatter.ofPattern("dd.MM.yyyy")));
	    original.setTheDateTime(java.time.LocalDateTime.parse("01.01.2001 10:15:30",java.time.format.DateTimeFormatter.ofPattern("dd.MM.yyyy k:mm:ss")));
	    original.setTheTime(java.time.LocalTime.parse("12:12:12",java.time.format.DateTimeFormatter.ofPattern("k:mm:ss")));
	    
	    // persist
	    original = repository.save(original);
	    
	    // check
	    DateEntity_ persisted = repository.findOne(original.getOid());
	    Assert.assertNotNull(persisted);
	    Assert.assertEquals(original, persisted);
	}
	
}
