/*
* Copyright (c): it@M - Dienstleister fuer Informations- und Telekommunikationstechnik
* der Landeshauptstadt Muenchen, 2018
*/
package de.muenchen.testproject.admin.thebackend.service.rest;

import java.math.BigDecimal;
import org.junit.Assert;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import de.muenchen.testproject.admin.thebackend.service.gen.domain.SecondLevelCyclicEntity_;
import java.util.Arrays;

import de.muenchen.testproject.admin.thebackend.service.MicroServiceApplication;
import de.muenchen.testproject.admin.thebackend.service.gen.domain.FirstLevelCyclicEntity_;

/*
 * This file will NOT be overwritten by Barrakuda.
 * This file was automatically generated by Barrakuda.
 */
@RunWith(SpringJUnit4ClassRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT, properties = {"spring.datasource.url=jdbc:h2:mem:testproject;DB_CLOSE_ON_EXIT=FALSE"})
@ContextConfiguration(classes={MicroServiceApplication.class})
@ActiveProfiles("test, no-security")
public class FirstLevelCyclicEntity_Repository_Test {

	@Autowired
	FirstLevelCyclicEntity_Repository repository;
	
	@Autowired
	SecondLevelCyclicEntity_Repository secondLevelCyclicEntity_Repository;
	
	@Test
	@Transactional(propagation=Propagation.REQUIRED, readOnly=false, noRollbackFor=Exception.class)
	public void testSave(){
	    
	    // initialize
	    FirstLevelCyclicEntity_ original = new FirstLevelCyclicEntity_();
	    original.setText1("text1");
	    
	    SecondLevelCyclicEntity_ reftosecond_1 = new SecondLevelCyclicEntity_();
	    reftosecond_1.setText2("text2");
	    original.getRefToSecond().add(reftosecond_1);
	    
	    // persist
	    reftosecond_1 = secondLevelCyclicEntity_Repository.save(reftosecond_1);
	    original = repository.save(original);
	    
	    // check
	    FirstLevelCyclicEntity_ persisted = repository.findOne(original.getOid());
	    Assert.assertNotNull(persisted);
	    Assert.assertEquals(original, persisted);
	}
	
}
