/*
* Copyright (c): it@M - Dienstleister fuer Informations- und Telekommunikationstechnik
* der Landeshauptstadt Muenchen, 2018
*/
package de.muenchen.testproject.admin.thebackend.service.rest;

import java.math.BigDecimal;
import org.junit.Assert;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.util.Arrays;
import de.muenchen.testproject.admin.thebackend.service.gen.domain.SecondRealtionEntity_;
import de.muenchen.testproject.admin.thebackend.service.gen.domain.FirstRealtionEntity_;

import de.muenchen.testproject.admin.thebackend.service.MicroServiceApplication;
import de.muenchen.testproject.admin.thebackend.service.gen.domain.TheBigEntity_;

/*
 * This file will NOT be overwritten by Barrakuda.
 * This file was automatically generated by Barrakuda.
 */
@RunWith(SpringJUnit4ClassRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT, properties = {"spring.datasource.url=jdbc:h2:mem:testproject;DB_CLOSE_ON_EXIT=FALSE"})
@ContextConfiguration(classes={MicroServiceApplication.class})
@ActiveProfiles("test, no-security")
public class TheBigEntity_Repository_Test {

	@Autowired
	TheBigEntity_Repository repository;
	
	@Autowired
	SecondRealtionEntity_Repository secondRealtionEntity_Repository;
	@Autowired
	FirstRealtionEntity_Repository firstRealtionEntity_Repository;
	
	@Test
	@Transactional(propagation=Propagation.REQUIRED, readOnly=false, noRollbackFor=Exception.class)
	public void testSave(){
	    
	    // initialize
	    TheBigEntity_ original = new TheBigEntity_();
	    original.setAttribute01("test");
	    original.setAttribute02("test");
	    
	    SecondRealtionEntity_ secondrelationotm_1 = new SecondRealtionEntity_();
	    secondrelationotm_1.setTheEntityText("test@test.de");
	    original.getSecondRelationOtm().add(secondrelationotm_1);
	    
	    SecondRealtionEntity_ secondrelationmtm_1 = new SecondRealtionEntity_();
	    secondrelationmtm_1.setTheEntityText("test@test.de");
	    original.getSecondRelationMtm().add(secondrelationmtm_1);
	    
	    SecondRealtionEntity_ secondrelationoto_1 = new SecondRealtionEntity_();
	    secondrelationoto_1.setTheEntityText("test@test.de");
	    original.setSecondRelationOto(secondrelationoto_1);
	    
	    SecondRealtionEntity_ secondrelationmto_1 = new SecondRealtionEntity_();
	    secondrelationmto_1.setTheEntityText("test@test.de");
	    original.setSecondRelationMto(secondrelationmto_1);
	    
	    FirstRealtionEntity_ firstrelationmtm_1 = new FirstRealtionEntity_();
	    firstrelationmtm_1.setTheEntityText("test@test.de");
	    original.getFirstRelationMtm().add(firstrelationmtm_1);
	    
	    // persist
	    secondrelationotm_1 = secondRealtionEntity_Repository.save(secondrelationotm_1);
	    secondrelationmtm_1 = secondRealtionEntity_Repository.save(secondrelationmtm_1);
	    secondrelationoto_1 = secondRealtionEntity_Repository.save(secondrelationoto_1);
	    secondrelationmto_1 = secondRealtionEntity_Repository.save(secondrelationmto_1);
	    firstrelationmtm_1 = firstRealtionEntity_Repository.save(firstrelationmtm_1);
	    original = repository.save(original);
	    
	    // check
	    TheBigEntity_ persisted = repository.findOne(original.getOid());
	    Assert.assertNotNull(persisted);
	    Assert.assertEquals(original, persisted);
	}
	
}
