/*
* Copyright (c): it@M - Dienstleister fuer Informations- und Telekommunikationstechnik
* der Landeshauptstadt Muenchen, 2018
*/
package de.muenchen.testproject.commons.domain;


import org.springframework.data.rest.webmvc.RepositorySearchesResource;
import org.springframework.hateoas.Link;
import org.springframework.hateoas.ResourceProcessor;
import org.springframework.stereotype.Component;

/*
 * This file will NOT be overwritten by Barrakuda.
 * This file was automatically generated by Barrakuda.
 */
@Component
public class SearchResourcesProcessor implements ResourceProcessor<RepositorySearchesResource> {

    private static final String FIND_FULL_TEXT_FUZZY = "findFullTextFuzzy";

    private static final String FIND_FULL_TEXT_JUNCTION = "findFullTextJunction";

    @Override
    public RepositorySearchesResource process(RepositorySearchesResource repositorySearchesResource) {

        final String search = repositorySearchesResource.getId().getHref();

        final Link findFullTextFuzzy = new Link(search + "/" + FIND_FULL_TEXT_FUZZY + "{?q}").withRel(FIND_FULL_TEXT_FUZZY);
        repositorySearchesResource.getLinks().add(0, findFullTextFuzzy);

        final Link findFullTextLucene = (new Link(search + "/" + FIND_FULL_TEXT_JUNCTION + "{?q}")).withRel(FIND_FULL_TEXT_JUNCTION);
        repositorySearchesResource.getLinks().add(1, findFullTextLucene);

        return repositorySearchesResource;

    }

}
