/*
* Copyright (c): it@M - Dienstleister fuer Informations- und Telekommunikationstechnik
* der Landeshauptstadt Muenchen, 2018
*/
package de.muenchen.testproject.commons.validator;

import javax.validation.ConstraintValidator;
import javax.validation.ConstraintValidatorContext;
import java.time.LocalDate;
import java.time.temporal.Temporal;

/*
 * This file will NOT be overwritten by Barrakuda.
 * This file was automatically generated by Barrakuda.
 */
/**
 * Validator for the Future annotation
 */
public class FutureValidator implements ConstraintValidator<Future, Temporal> {

    @Override
    public void initialize(Future constraintAnnotation) {
        // nuttin to do here
    }

    @Override
    public boolean isValid(Temporal value, ConstraintValidatorContext context) {
        return value == null ? true : LocalDate.from(value).isAfter(LocalDate.now());
    }

}
