/*
* Copyright (c): it@M - Dienstleister fuer Informations- und Telekommunikationstechnik
* der Landeshauptstadt Muenchen, 2018
*/
package de.muenchen.testproject.admin.thebackend.service.services.event;

import org.springframework.stereotype.Service;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import de.muenchen.testproject.admin.thebackend.service.gen.domain.CustomEntity_;
import de.muenchen.testproject.admin.thebackend.service.gen.services.event.CustomEntity_EventService;

/*
 * This file will NOT be overwritten by Barrakuda.
 * This file was automatically generated by Barrakuda.
 */
/**
 * Provides methods to implement logic before and after Events.
 * If used as generated by Barrakuda this service will be autowired and called by CustomEntity_EventListener.
 */
@Service
public class CustomEntity_EventServiceImpl implements CustomEntity_EventService {
	
	private static final Logger LOG = LoggerFactory.getLogger(CustomEntity_EventServiceImpl.class);
	
	// If you need access to the database you can autowire a Repository.
	// Repositories are generated into the package: .gen.rest
	//
	// @Autowired
	// private <EntityName>Repository repo;
	
	@Override
	public void onAfterCreate(CustomEntity_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeCreate(CustomEntity_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeSave(CustomEntity_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterSave(CustomEntity_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkSave(CustomEntity_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkSave(CustomEntity_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkDelete(CustomEntity_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeDelete(CustomEntity_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterDelete(CustomEntity_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkDelete(CustomEntity_ parent, Object linked) {
		// Add your logic here.
	}
}
