/*
* Copyright (c): it@M - Dienstleister fuer Informations- und Telekommunikationstechnik
* der Landeshauptstadt Muenchen, 2018
*/
package de.muenchen.testproject.admin.thebackend.service.services.event;

import org.springframework.stereotype.Service;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import de.muenchen.testproject.admin.thebackend.service.gen.domain.DateEntity_;
import de.muenchen.testproject.admin.thebackend.service.gen.services.event.DateEntity_EventService;

/*
 * This file will NOT be overwritten by Barrakuda.
 * This file was automatically generated by Barrakuda.
 */
/**
 * Provides methods to implement logic before and after Events.
 * If used as generated by Barrakuda this service will be autowired and called by DateEntity_EventListener.
 */
@Service
public class DateEntity_EventServiceImpl implements DateEntity_EventService {
	
	private static final Logger LOG = LoggerFactory.getLogger(DateEntity_EventServiceImpl.class);
	
	// If you need access to the database you can autowire a Repository.
	// Repositories are generated into the package: .gen.rest
	//
	// @Autowired
	// private <EntityName>Repository repo;
	
	@Override
	public void onAfterCreate(DateEntity_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeCreate(DateEntity_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeSave(DateEntity_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterSave(DateEntity_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkSave(DateEntity_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkSave(DateEntity_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkDelete(DateEntity_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeDelete(DateEntity_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterDelete(DateEntity_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkDelete(DateEntity_ parent, Object linked) {
		// Add your logic here.
	}
}
