/*
* Copyright (c): it@M - Dienstleister fuer Informations- und Telekommunikationstechnik
* der Landeshauptstadt Muenchen, 2018
*/
package de.muenchen.testproject.admin.thebackend.service.services.event;

import org.springframework.stereotype.Service;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import de.muenchen.testproject.admin.thebackend.service.gen.domain.Fall_;
import de.muenchen.testproject.admin.thebackend.service.gen.services.event.Fall_EventService;

/*
 * This file will NOT be overwritten by Barrakuda.
 * This file was automatically generated by Barrakuda.
 */
/**
 * Provides methods to implement logic before and after Events.
 * If used as generated by Barrakuda this service will be autowired and called by Fall_EventListener.
 */
@Service
public class Fall_EventServiceImpl implements Fall_EventService {
	
	private static final Logger LOG = LoggerFactory.getLogger(Fall_EventServiceImpl.class);
	
	// If you need access to the database you can autowire a Repository.
	// Repositories are generated into the package: .gen.rest
	//
	// @Autowired
	// private <EntityName>Repository repo;
	
	@Override
	public void onAfterCreate(Fall_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeCreate(Fall_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeSave(Fall_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterSave(Fall_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkSave(Fall_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkSave(Fall_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkDelete(Fall_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeDelete(Fall_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterDelete(Fall_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkDelete(Fall_ parent, Object linked) {
		// Add your logic here.
	}
}
