/*
* Copyright (c): it@M - Dienstleister fuer Informations- und Telekommunikationstechnik
* der Landeshauptstadt Muenchen, 2018
*/
package de.muenchen.testproject.admin.thebackend.service.services.event;

import org.springframework.stereotype.Service;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import de.muenchen.testproject.admin.thebackend.service.gen.domain.FirstLevelCyclicEntity_;
import de.muenchen.testproject.admin.thebackend.service.gen.services.event.FirstLevelCyclicEntity_EventService;

/*
 * This file will NOT be overwritten by Barrakuda.
 * This file was automatically generated by Barrakuda.
 */
/**
 * Provides methods to implement logic before and after Events.
 * If used as generated by Barrakuda this service will be autowired and called by FirstLevelCyclicEntity_EventListener.
 */
@Service
public class FirstLevelCyclicEntity_EventServiceImpl implements FirstLevelCyclicEntity_EventService {
	
	private static final Logger LOG = LoggerFactory.getLogger(FirstLevelCyclicEntity_EventServiceImpl.class);
	
	// If you need access to the database you can autowire a Repository.
	// Repositories are generated into the package: .gen.rest
	//
	// @Autowired
	// private <EntityName>Repository repo;
	
	@Override
	public void onAfterCreate(FirstLevelCyclicEntity_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeCreate(FirstLevelCyclicEntity_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeSave(FirstLevelCyclicEntity_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterSave(FirstLevelCyclicEntity_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkSave(FirstLevelCyclicEntity_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkSave(FirstLevelCyclicEntity_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkDelete(FirstLevelCyclicEntity_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeDelete(FirstLevelCyclicEntity_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterDelete(FirstLevelCyclicEntity_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkDelete(FirstLevelCyclicEntity_ parent, Object linked) {
		// Add your logic here.
	}
}
