/*
* Copyright (c): it@M - Dienstleister fuer Informations- und Telekommunikationstechnik
* der Landeshauptstadt Muenchen, 2018
*/
package de.muenchen.testproject.admin.thebackend.service.services.event;

import org.springframework.stereotype.Service;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import de.muenchen.testproject.admin.thebackend.service.gen.domain.TheBigEntity_;
import de.muenchen.testproject.admin.thebackend.service.gen.services.event.TheBigEntity_EventService;

/*
 * This file will NOT be overwritten by Barrakuda.
 * This file was automatically generated by Barrakuda.
 */
/**
 * Provides methods to implement logic before and after Events.
 * If used as generated by Barrakuda this service will be autowired and called by TheBigEntity_EventListener.
 */
@Service
public class TheBigEntity_EventServiceImpl implements TheBigEntity_EventService {
	
	private static final Logger LOG = LoggerFactory.getLogger(TheBigEntity_EventServiceImpl.class);
	
	// If you need access to the database you can autowire a Repository.
	// Repositories are generated into the package: .gen.rest
	//
	// @Autowired
	// private <EntityName>Repository repo;
	
	@Override
	public void onAfterCreate(TheBigEntity_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeCreate(TheBigEntity_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeSave(TheBigEntity_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterSave(TheBigEntity_ entity) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkSave(TheBigEntity_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkSave(TheBigEntity_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeLinkDelete(TheBigEntity_ parent, Object linked) {
		// Add your logic here.
	}
	@Override
	public void onBeforeDelete(TheBigEntity_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterDelete(TheBigEntity_ entity) {
		// Add your logic here.
	}
	@Override
	public void onAfterLinkDelete(TheBigEntity_ parent, Object linked) {
		// Add your logic here.
	}
}
