/*
* Copyright (c): it@M - Dienstleister fuer Informations- und Telekommunikationstechnik
* der Landeshauptstadt Muenchen, 2018
*/
package de.muenchen.testproject.admin.thebackend.service.services.businessactions;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Map;

import org.springframework.security.access.prepost.PreAuthorize;
import de.muenchen.testproject.admin.thebackend.service.gen.services.businessactions.TheTest_BusinessActionService;

/*
 * This file will NOT be overwritten by Barrakuda.
 * This file was automatically generated by Barrakuda.
 */
/**
 * Provides a service to execute business-actions.
 * If used as generated by Barrakuda this service will be autowired and called by BusinessActionController.
 */
@Service
@PreAuthorize("hasPermission(T(de.muenchen.testproject.admin.thebackend.service.gen.security.ResourcesEnum).thebackend_BUSINESSACTION_TheTest.name(),'Entitlements')")
public class TheTest_BusinessActionServiceImpl implements TheTest_BusinessActionService {
	
	private static final Logger LOG = LoggerFactory.getLogger(TheTest_BusinessActionServiceImpl.class);
	
	// If you need access to the database you can autowire a Repository.
	// Repositories are generated into the package: .gen.rest
	//
	// @Autowired
	// private <EntityName>Repository repo;

	/**
	 * This BusinessAction's purpose is: test
	 * It returns multiple String.
	 * TODO: Implement
	 */
	@Override
	public java.util.List<String> theTest(Map<String, Object> header, 
			java.util.List<String> nameList,
			String name) {
		// Stop if parameters are null
		java.util.List<String> nullParams = new java.util.ArrayList<>();
		if(nameList==null) nullParams.add("nameList");
		if(name==null) nullParams.add("name");
		if(!nullParams.isEmpty()){
			throw new IllegalArgumentException("Expected values in body: java.util.List<String> nameList, String name - Missing "+nullParams);
		}
		return null;
		//throw new UnsupportedOperationException("The BusinessAction thetest is not yet implemented!");
	}
	
}
