/*
* Copyright (c): it@M - Dienstleister fuer Informations- und Telekommunikationstechnik
* der Landeshauptstadt Muenchen, 2018
*/
package de.muenchen.testproject.admin.thebackend.service.services.resource;

import de.muenchen.testproject.admin.thebackend.service.MicroServiceApplication;
import de.muenchen.testproject.admin.thebackend.service.gen.domain.CustomEntity_;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.hateoas.Resource;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;


/*
 * This file will NOT be overwritten by Barrakuda.
 * This file was automatically generated by Barrakuda.
 */
@RunWith(SpringJUnit4ClassRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ContextConfiguration(classes={MicroServiceApplication.class})
@ActiveProfiles("test, no-security")
public class CustomEntity_ResourceServiceImplTest {
	
    @Autowired
    private CustomEntity_ResourceServiceImpl customEntityResourceServiceImpl;
	
	@Test
	public void processTest() {
	    
	    CustomEntity_ customEntity = new CustomEntity_();
	    Resource<CustomEntity_> customEntityResource = new Resource<>(customEntity);
	    int customEntityResourceHash = customEntityResource.hashCode();
	    customEntityResource = customEntityResourceServiceImpl.process(customEntityResource);
	    Assert.assertEquals(customEntityResourceHash, customEntityResource.hashCode());
	    
	    
	}
	
}
