/*
* Copyright (c): it@M - Dienstleister fuer Informations- und Telekommunikationstechnik
* der Landeshauptstadt Muenchen, 2018
*/
package de.muenchen.testproject.admin.thebackend.service.services.resource;

import de.muenchen.testproject.admin.thebackend.service.MicroServiceApplication;
import de.muenchen.testproject.admin.thebackend.service.gen.domain.DateEntity_;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.hateoas.Resource;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;


/*
 * This file will NOT be overwritten by Barrakuda.
 * This file was automatically generated by Barrakuda.
 */
@RunWith(SpringJUnit4ClassRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ContextConfiguration(classes={MicroServiceApplication.class})
@ActiveProfiles("test, no-security")
public class DateEntity_ResourceServiceImplTest {
	
    @Autowired
    private DateEntity_ResourceServiceImpl dateEntityResourceServiceImpl;
	
	@Test
	public void processTest() {
	    
	    DateEntity_ dateEntity = new DateEntity_();
	    Resource<DateEntity_> dateEntityResource = new Resource<>(dateEntity);
	    int dateEntityResourceHash = dateEntityResource.hashCode();
	    dateEntityResource = dateEntityResourceServiceImpl.process(dateEntityResource);
	    Assert.assertEquals(dateEntityResourceHash, dateEntityResource.hashCode());
	    
	    
	}
	
}
