/*
* Copyright (c): it@M - Dienstleister fuer Informations- und Telekommunikationstechnik
* der Landeshauptstadt Muenchen, 2018
*/
package de.muenchen.testproject.admin.thebackend.service.services.resource;

import de.muenchen.testproject.admin.thebackend.service.MicroServiceApplication;
import de.muenchen.testproject.admin.thebackend.service.gen.domain.FirstLevelEntity_;
import de.muenchen.testproject.admin.thebackend.service.gen.domain.SecondLevelEntity_;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.hateoas.Resource;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;


/*
 * This file will NOT be overwritten by Barrakuda.
 * This file was automatically generated by Barrakuda.
 */
@RunWith(SpringJUnit4ClassRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ContextConfiguration(classes={MicroServiceApplication.class})
@ActiveProfiles("test, no-security")
public class FirstLevelEntity_ResourceServiceImplTest {
	
    @Autowired
    private FirstLevelEntity_ResourceServiceImpl firstLevelEntityResourceServiceImpl;
	
	@Test
	public void processTest() {
	    
	    FirstLevelEntity_ firstLevelEntity = new FirstLevelEntity_();
	    Resource<FirstLevelEntity_> firstLevelEntityResource = new Resource<>(firstLevelEntity);
	    int firstLevelEntityResourceHash = firstLevelEntityResource.hashCode();
	    firstLevelEntityResource = firstLevelEntityResourceServiceImpl.process(firstLevelEntityResource);
	    Assert.assertEquals(firstLevelEntityResourceHash, firstLevelEntityResource.hashCode());
	    
	    SecondLevelEntity_ secondLevelEntity = new SecondLevelEntity_();
	    Resource<FirstLevelEntity_> secondLevelEntityResource = new Resource<>(secondLevelEntity);
	    int secondLevelEntityResourceHash = secondLevelEntityResource.hashCode();
	    secondLevelEntityResource = firstLevelEntityResourceServiceImpl.process(secondLevelEntityResource);
	    Assert.assertEquals(secondLevelEntityResourceHash, secondLevelEntityResource.hashCode());
	    
	    
	}
	
}
