/*
* Copyright (c): it@M - Dienstleister fuer Informations- und Telekommunikationstechnik
* der Landeshauptstadt Muenchen, 2018
*/
package de.muenchen.testproject.admin.thebackend.service.services.resource;

import de.muenchen.testproject.admin.thebackend.service.MicroServiceApplication;
import de.muenchen.testproject.admin.thebackend.service.gen.domain.TheBigEntity_;
import de.muenchen.testproject.admin.thebackend.service.gen.domain.TheBigEntity_InlineProjection;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.hateoas.Resource;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;


/*
 * This file will NOT be overwritten by Barrakuda.
 * This file was automatically generated by Barrakuda.
 */
@RunWith(SpringJUnit4ClassRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ContextConfiguration(classes={MicroServiceApplication.class})
@ActiveProfiles("test, no-security")
public class TheBigEntity_ResourceServiceImplTest {
	
    @Autowired
    private TheBigEntity_ResourceServiceImpl theBigEntityResourceServiceImpl;
	
	@Test
	public void processTest() {
	    
	    TheBigEntity_ theBigEntity = new TheBigEntity_();
	    Resource<TheBigEntity_> theBigEntityResource = new Resource<>(theBigEntity);
	    int theBigEntityResourceHash = theBigEntityResource.hashCode();
	    theBigEntityResource = theBigEntityResourceServiceImpl.process(theBigEntityResource);
	    Assert.assertEquals(theBigEntityResourceHash, theBigEntityResource.hashCode());
	    
	    
	}
	
}
