# GLOBAL CONFIGURATION
spring:
    # if you want to set a different profile
    # use environment variable:
    #
    # SPRING_PROFILES_ACTIVE=docker
    profiles.active: local
    application.name: Zuul


---
# LOCAL CONFIGURATION
spring:
    profiles: local

server:
    port: 8082
    ssl:
       enabled: true
       keyAlias: selfsigned_localhost_sslserver
       key-store-password: changeit
       #key-password: changeit
       key-store: classpath:localhost.jks
       key-store-provider: SUN
       keyStoreType: JKS


zuul:
  #sslHostnameValidationEnabled: false
  ignoredServices: '*'
  host:
    socket-timeout-millis: 120000
  routes:
    user:
      path: /api/user_service/**
      url: https://localhost:8870/
      add-proxy-headers: true
    thebackend:
      path: /api/testproject-thebackend-service/**
      url: https://localhost:39146/
      add-proxy-headers: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: ${zuul.host.socket-timeout-millis}

security:
  oauth2:
    client:
      clientId: openIdDemo
      clientSecret: 47f8baf3-ed3c-481f-b171-535d91b885c3
      accessTokenUri: http://localhost:8080/auth/realms/demo/protocol/openid-connect/token
      userAuthorizationUri: http://localhost:8080/auth/realms/demo/protocol/openid-connect/auth
    resource:
      jwt:
        key-value: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAr1aJe3anRtLHLbJJ/z+FI3p6uJbypBM5llSJ41cv0s5X2gDjO/EsEmngDf8Ypo4gTdTwwWTLoTgJWK1KVveiX5TUIxiEbpjaVAiKzc3IXNMrq+6DMcyrDiyVjAsWkleAAmQJJwnsp7vv0/1IRIdj6t3r4+CUQOp3PiBPojRh7QGZxuU0MbsgwBKAW1AUyM17F2knovpshi9crwzwf47p3xa6uGJYHx+iAV7ritgC6QYWwg92PT2nXMUQbo+VllRb/gwvWdrIuybKUBlXZ59/M2greCudYjGhn0g5l236ADZYvGfxl8lk+x1ZHhX6Rp5IAWM8rrCjEoVdP2PUXPIadQIDAQAB
  sessions: ALWAYS

endpoints.routes.sensitive: false
       
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG      
      
---
# DOCKER CONFIGURATION
spring:
    profiles: docker
---
# NO-SECURITY CONFIGURATION
spring:
    profiles: no-security
    h2.console.enabled: true

security.ignored: /**    

      
---
# OPENSHIFT CONFIGURATION
spring:
    profiles: openshift

server.port: 8080

# zuul routes
zuul:
  ignoredServices: '*'
  routes:
    user:
      path: /api/user_service/**
      url: http://user-service:8080/
      add-proxy-headers: true
    thebackend:
      path: /api/testproject-thebackend-service/**
      url: http://testproject-thebackend-service:8080/
      add-proxy-headers: true 

security:
  oauth2:
    client:
      clientId: openIdDemo
      clientSecret: 57446039-4005-493a-9e94-137424d599d8
      accessTokenUri: https://ssodev.muenchen.de/auth/realms/demo/protocol/openid-connect/token
      userAuthorizationUri: https://ssodev.muenchen.de/auth/realms/demo/protocol/openid-connect/auth
    resource:
      jwt:
        key-value: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5YUs1ITW6qEbxlc93i0BAWYfhdpH94WcGlYS8ayzoKJA8G3QN4JiAn4Wp4VwCuUkf3bh3Y1YdFqlN42Rz5DeTi86Wilhle2fJthboBneGiaQZvszdGz8wMNcdqDC45dTLunJ5PnesVoMK6OQ/osk+7t/04QsMSJZtD+QodaKtj2a1KyUXBlX0yclG6R+XrzP2BSh4ixuiwwnFu8tffqOOmNMmtiNj4nS20S0P82QLXVhjy4NgP4UHXpLGtD1pJFQRO2MXh+N7NEVZrF76fIXTtmqGq0I/Ko87vjGxTEDcZNC/oWFRLkiEVtB+eSYM+NeB4vMhgIygbqt+4+YlQf0hQIDAQAB
  sessions: ALWAYS

endpoints.routes.sensitive: false
