/*
* Copyright (c): it@M - Dienstleister fuer Informations- und Telekommunikationstechnik
* der Landeshauptstadt Muenchen, 2018
*/
package de.muenchen.testproject.commons.exceptions;


import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ResponseStatus;

/*
 * This file will NOT be overwritten by Barrakuda.
 * This file was automatically generated by Barrakuda.
 */
/**
 *
 * @author roland
 */
@ResponseStatus(value=HttpStatus.PAYLOAD_TOO_LARGE, reason="too many search results")  // 413
public class TooManyResultsException extends Exception {

    private final int maxResults;

    public TooManyResultsException(int maxResults) {
        this.maxResults = maxResults;
    }

    public int getMaxResults() {
        return maxResults;
    }

}
