/*
* Copyright (c): it@M - Dienstleister fuer Informations- und Telekommunikationstechnik
* der Landeshauptstadt Muenchen, 2018
*/
package de.muenchen.testproject.commons.auditing;

import org.springframework.data.repository.CrudRepository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import java.util.UUID;

/*
 * This file will NOT be overwritten by Barrakuda.
 * This file was automatically generated by Barrakuda.
 */
/**
 * Repository-Zugriff für AuditingUserEntities.
 * Created by fabian.holtkoetter on 08.09.15.
 */
@RepositoryRestResource(
		exported = true,
        path="auditingUserEntities",
        collectionResourceRel="auditingUserEntities")
public interface AuditingUserRepository extends CrudRepository<AuditingUserEntity, UUID> {

}
