/*
* Copyright (c): it@M - Dienstleister fuer Informations- und Telekommunikationstechnik
* der Landeshauptstadt Muenchen, 2018
*/
package de.muenchen.testproject.commons.auditing;

import java.util.Queue;
import java.util.concurrent.LinkedBlockingQueue;

/*
 * This file will NOT be overwritten by Barrakuda.
 * This file was automatically generated by Barrakuda.
 */
/**
 * Queue zum Puffern von AuditingEvents
 * Created by fabian.holtkoetter on 17.09.15.
 */
public class EntitySaveQueue {
    private Queue<AuditingUserEntity> entities = new LinkedBlockingQueue<>();
    private boolean available = false;


    public synchronized AuditingUserEntity get() {
        while (!available) {
            try {
                wait();
            } catch (InterruptedException e) {
                throw new AssertionError("Can not happen.");
            }
        }
        available = !entities.isEmpty();
        return entities.poll();
    }

    public synchronized void put(AuditingUserEntity entity) {
        entities.add(entity);
        available = true;
        notifyAll();
    }

}
