/*
* Copyright (c): it@M - Dienstleister fuer Informations- und Telekommunikationstechnik
* der Landeshauptstadt Muenchen, 2018
*/
package de.muenchen.testproject.admin.thebackend.service.services.businessactions;

import de.muenchen.testproject.admin.thebackend.service.MicroServiceApplication;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;


/*
 * This file will NOT be overwritten by Barrakuda.
 * This file was automatically generated by Barrakuda.
 */
@RunWith(SpringJUnit4ClassRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ContextConfiguration(classes={MicroServiceApplication.class})
@ActiveProfiles("test, no-security")
public class TheTest_BusinessActionServiceImplTest {

	@Autowired
	private TheTest_BusinessActionServiceImpl theTestBusinessActionServiceImpl;

	@Test(expected = IllegalArgumentException.class)
	public void theTestIllegalArgumentExceptionTest() {
		theTestBusinessActionServiceImpl.theTest(null,
				null,
				null);
	}

	@Test(expected = UnsupportedOperationException.class)
	public void theTestUnsupportedOperationExceptionTest() {
		
		java.util.List<String> nameList = new java.util.ArrayList<String>();
		String name = "test_data";
		
		theTestBusinessActionServiceImpl.theTest(null,
				nameList,
				name);
		
	}
	
}
