/*
* Copyright (c): it@M - Dienstleister fuer Informations- und Telekommunikationstechnik
* der Landeshauptstadt Muenchen, 2018
*/
package de.muenchen.testproject.admin.thebackend.client.businessactions;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.web.client.RestTemplate;

import java.net.URI;

/*
 * This file will NOT be overwritten by Barrakuda.
 * This file was automatically generated by Barrakuda.
 */
/**
 * A concrete implementation of the BusinessActionsRestClientImpl with a RestTemplate of the server.
 * It can be used to create additional method to enhance this rest client.
 */
public class BusinessActionsRestClientImpl extends BusinessActionsRestClientAbstract {

    private static final Logger LOG = LoggerFactory.getLogger(BusinessActionsRestClientImpl.class);

    /**
     * Creates a new concrete implementation of BusinessActionsRestClientImpl by RestTemplate of the server.
     * @param restTemplate The restTemplate for the HTTP Requests.
     * @param basePath The base path for the HTTP Requests.
     */
    public BusinessActionsRestClientImpl(RestTemplate restTemplate, final URI basePath) {
        super(restTemplate, basePath);
    }

    /**
     * Creates a new concrete implementation of BusinessActionsRestClientImpl by RestTemplate of the server.
     * @param restTemplate The restTemplate for the HTTP Requests.
     * @param basePath The base path for the HTTP Requests.
     */
    public BusinessActionsRestClientImpl(RestTemplate restTemplate, final String basePath) {
        this(restTemplate, URI.create(basePath));
    }

}
