/*
* Copyright (c): it@M - Dienstleister fuer Informations- und Telekommunikationstechnik
* der Landeshauptstadt Muenchen, 2018
*/
package de.muenchen.testproject.admin.thebackend.client.businessactions;


/*
 * This file will be overwritten on every change of the model!
 * This file was automatically generated by Barrakuda.
 */
/**
 * Provides a simple Interface for the BusinessActions.
 */
public interface BusinessActionsRestClient {
	
	/**
	 * This BusinessAction's purpose is: test
	 * It returns multiple String.
	 */
	java.util.List<String> theTest(java.util.List<String> nameList,
			String name);
}
