/*
* Copyright (c): it@M - Dienstleister fuer Informations- und Telekommunikationstechnik
* der Landeshauptstadt Muenchen, 2018
*/
package de.muenchen.testproject.commons.authorization;

import java.io.Serializable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Profile;
import org.springframework.security.access.PermissionEvaluator;
import org.springframework.security.core.Authentication;
import org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationDetails;
import org.springframework.stereotype.Service;


/*
 * This file will NOT be overwritten by Barrakuda.
 * This file was automatically generated by Barrakuda.
 */
/**
 *
 * @author Roland.Werner
 */
@Service
@Profile("!no-security")
public class CustomPermissionEvaluator implements PermissionEvaluator {

    private static final Logger LOG = LoggerFactory.getLogger(CustomPermissionEvaluator.class);
    
    @Autowired    
    private PermissionsService permissionsService;
    
    @Override
    public boolean hasPermission(Authentication a, Object o, Object o1) {
        return hasPermission(a, 1, (String) o, o1);
    }

    /**
     * Prüft die übergebene Permission gegen KeyCloak. Holt sich dafür den Token des aktuellen Users.
     * @param a
     * @param srlzbl
     * @param permission die zu überprüfende Permission
     * @param methodObject welche Methode anzuwenden ist: a) Entitlements, b) EntitlementsKeyCloakAPI, c) EntitlementsNoCache
     * @return 
     */
    @Override
    public boolean hasPermission(Authentication a, Serializable srlzbl, String permission, Object methodObject) {
        LOG.info("---------------------------");
        LOG.info("-- hasPermission called. --");
        LOG.info("---------------------------");
        OAuth2AuthenticationDetails details = (OAuth2AuthenticationDetails) a.getDetails();
        String tokenValue = details.getTokenValue();          
        
        String method = (String) methodObject;
        
        boolean allowed = false;
        if (method.equals("Entitlements")) {
            allowed = this.permissionsService.check(permission, tokenValue, true);
        } else if (method.equals("EntitlementsNoCache")) {
            allowed = this.permissionsService.check(permission, tokenValue, false);
        }  
        else {
            LOG.error("Supplied method " + method + " not supported!");
        }
        return allowed;
    }
    
}
