/*
* Copyright (c): it@M - Dienstleister fuer Informations- und Telekommunikationstechnik
* der Landeshauptstadt Muenchen, 2018
*/
package de.muenchen.testproject.commons.authorization;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cache.Cache;
import org.springframework.cache.CacheManager;


/*
 * This file will NOT be overwritten by Barrakuda.
 * This file was automatically generated by Barrakuda.
 */
/**
 *
 * @author roland
 */
public class PermissionsCache {

    private final static String PERMISSIONS_CACHE = "permissionsCache";

    @Autowired
    private CacheManager cacheManager;
    
    public Cache getCache() {
        return cacheManager.getCache(PERMISSIONS_CACHE);
    }

}
